### ISSUE TITLE
Background mode

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-ios#10]
Hi, @hectorerb.

This is a reference about the background modes.

https://www.raywenderlich.com/143128/background-modes-tutorial-getting-started

Good luck.

**Comment by hectorerb** [comment]
This article explains when is possible to run an app in background

https://stackoverflow.com/questions/11044095/ios-keep-an-app-running-like-a-service

**Comment by ajsb85** [comment]
@hectorerb We have process as foreground, process as background and process as service.

**Comment by hectorerb** [comment]
@ajsb85 in iOS we only have process as foreground and background
