### ISSUE TITLE
How-tos and development documentation

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-ios#124]
Hi, @Naylin15 

Change the name "Wiki" to "How-tos" and add these articles; and add the sub menu items to the Development section. If these pages does not exist, please, create an issue and request it. 👍 

**How-tos**

- [x] How to install
- [x] How to use
- [x] Use Cases
- [x] How it works
- [x] How to contribute
- [x] How to Translate

**Development**

- [x] Code documentation
- [x] Code coverage
- [x] Test report

**Comment by Naylin15** [comment]
Hi @hectorerb,

We need to add the information for the Test Report on the project site

Thanks

**Comment by Naylin15** [comment]
The final article was added in [06ffbd0](https://github.com/flyve-mdm/ios-mdm-agent/commit/06ffbd03edfc3d1e3335d71c92fad6b3b00c9087)

Since the Test report has its own issue, I'll close this issue
