### ISSUE TITLE
What type of accounts we required to implement MDM?

### ISSUE THREAD

**Issue by Lyankar** [flyve-mdm/flyve-mdm-ios#153]
Hai, this is Lyankar. To implement MDM what type accounts we required, which means prerequisites. Actually some other MDM's requires Apple Enterprise account, Apple Developer account and Apple DEP etc. So please explain.

And please provide if any tutorials available to implement Flyve-MDM.

**Comment by ajsb85** [comment]
Duplicated:
https://github.com/flyve-mdm/ios-inventory-agent/issues/159
