### ISSUE TITLE
Supervisor screen - Mobile Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-ios#20]
Provide help desk information or simple organization or the owner of the entity that have the supervision control of the device.

![artboard 2](https://user-images.githubusercontent.com/663460/27650567-a28daa28-5c35-11e7-808a-a82a4a3144f1.png)

**Comment by btry** [comment]
Enhancements on the itemtype PluginFlyvemdmEntityConfig in progress

new fields are: 
* support_name
* support_phone
* support_website
* support_address
* support_email

**Comment by ajsb85** [comment]
@btry Perfect
