### ISSUE TITLE
Screen to fill user information - Mobile Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-ios#26]
Screen after click to start the enrollment procedure

![artboard 8](https://user-images.githubusercontent.com/663460/27650568-a2a3643a-5c35-11e7-8fef-3fe827bb1952.png)

**Comment by ajsb85** [comment]
Hi, @btry 

Can we update the photo of the user with the API?
Could you create a Postman and/or cURL example for @hectorerb?

Thanks.

**Comment by hectorerb** [comment]
@ajsb85  just now, The photo is not sent to the API
