### ISSUE TITLE
Create project page

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-ios#71]
Hi, @ajsb85.

I will create the `gh-pages` as requested in this issue: flyve-mdm/flyve-mdm.github.io#13

Regards.

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Please, re-create the gh-pages branch as orphan and empty.

Following these steps:
https://help.github.com/articles/creating-project-pages-using-the-command-line/

And please, add your issues and PRs with the Project ID 2 (Website) of this repository.

Thanks.

**Comment by ajsb85** [comment]
Hi, @hectorerb 

The project site is here at the moment:
http://flyve.org/flyve-mdm-ios-agent/

I wil close this issue.

Good job @Gianfranco97
