### ISSUE TITLE
Generate automatic release

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-ios#79]
Hi, @hectorerb.

Could you generate automatic release description from git metadata
https://github.com/conventional-changelog/conventional-github-releaser

The idea is to create a link with the reference to download the files.

Regards.

**Comment by ajsb85** [comment]
Hi, @hectorerb  
 
I think, this issue is ready to close. 
Could you confirm and close? 
 
Thanks.

**Comment by hectorerb** [comment]
yes, done!

ref: https://github.com/flyve-mdm/flyve-mdm-ios-agent/pull/93
