### ISSUE TITLE
Generate automatic version number

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/flyve-mdm-ios#90]
Hi, @ajsb85

I will generate automatic version number with this tool:
https://github.com/conventional-changelog/standard-version

Best regards.

**Comment by ajsb85** [comment]
Hi, @hectorerb 

With this tool CLI, you can get the version name proposed by the commit history.
https://www.npmjs.com/package/conventional-recommended-bump
So you can store in the proper var inside the project.

Regards.
