### ISSUE TITLE
Use iTunes Connect API with Spaceship

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/flyve-mdm-ios#91]
Hi, @ajsb85

I will change connect to iTunes Connect API from fastlane tools to spaceship.

Reference:
https://github.com/fastlane/fastlane/tree/master/spaceship

Best regards.

**Comment by ajsb85** [comment]
Hi, @hectorerb  
 
I think, this issue is ready to close. 
Could you confirm and close? 
 
Thanks.
