### ISSUE TITLE
Press release article

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-ios#92]
Hi, @Naylin15  

Please, help me to write a welcome article for the page, this first article should give a brief introduction to the product and serve as an entry point for for new users. The idea is to be able to use this for promotion.

Said article should be written in Markdown and be published in the branch of gh-pages within the folder "_post"

Steps to follow for publication:
1. Enter http://prose.io/
2. Select the Flyve MDM organization
3. Enter in repository where you want to publish the article
4. Change to the branch gh-pages
5. Click on the "NEW FILE" button
6. Write your article
7. Save your work

Thanks.

**Comment by mmillevoye** [comment]
Ok, can you write down the main info about 'introduction to the product' so i can transform it on a welcoming article ? I don't know what you want to highlight. Thanks :)

**Comment by ajsb85** [comment]
Hi, @Naylin15 

Could you move from HackMD the press release draft to the news section of the project site using prose.io and reference this task?

**Comment by Naylin15** [comment]
Hi, @ajsb85 

This is done in [c8ca018](https://github.com/flyve-mdm/flyve-mdm-ios-agent/commit/c8ca01868f17c782c0e8bfeffbec95620cfd0576)
